# Generated by Django 5.0.1 on 2024-02-02 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_photo_alter_articles_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 2, 12, 7, 55, 285844, tzinfo=datetime.timezone.utc)),
        ),
    ]
