# Generated by Django 5.0.2 on 2024-02-17 20:12

import datetime
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articles_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 17, 20, 12, 54, 428283, tzinfo=datetime.timezone.utc)),
        ),
    ]
