# Generated by Django 5.0.2 on 2024-02-18 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articles_published_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 18, 15, 42, 9, 88368, tzinfo=datetime.timezone.utc)),
        ),
    ]
